name: air_analyzer_android
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.16.0
  firebase_database: ^10.3.1
  flutter_local_notifications: ^16.3.0
  workmanager: ^0.5.1
  flutter_reactive_ble: ^5.0.2
  permission_handler: ^10.4.0
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
